[Interface]
# PEAK-WG — Sanoj James (10.80.200.7)
PrivateKey = GCNMl8wHXLnsgrAdKhBY0eTnd9yaulYZvBjF7gaz3HY=
Address = 10.80.200.7/32
DNS = 10.80.100.1

[Peer]
PublicKey = MCUPmFkyIS6C6nFn0ccrt6uNh7EHDJP9NDkqDueifxo=
Endpoint = 125.19.224.18:51820
# Alternate if Airtel is down: 47.247.169.94:51820
AllowedIPs = 10.80.0.0/16
PersistentKeepalive = 25
